blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .feeds import BlogPostFeed

# Patterns of different paths
urlpatterns = [
    # path('', views.BlogPostListView.as_view(), name='blog_post_list'),
    path('', views.blog_post_list, name='blog_post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.blog_post_detail, name='blog_post_detail'),
    path('<int:blog_post_id>/sharing/', views.sharing_post, name='sharing_post'),
    path('tag/<slug:slug_tag>/', views.blog_post_list, name='blog_post_list_with_tag'),
    path('feed/', BlogPostFeed(), name='feed'),
    path('search/', views.search_engine, name='search_post'),

]

hipal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogPostSitemap
import languages
from languages.views import custom_logout_view

sitemaps = {
    'posts': BlogPostSitemap,
}


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('languages.urls')),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
                  # path('accounts/login/', views.LoginView.as_view(), name='login'),
                  # path('accounts/logout/', languages.views.custom_logout_view, name='logout'),
                  path('accounts/logout/', views.LogoutView.as_view(template_name='registration/logout.html'),
                       name='logout'),
                  path('', include('students.urls')),
                  path('messaging/', include('message_chat.urls', namespace='message_chat')),
                  path('restapi/', include('languages.restapi.urls', namespace='restapi')),
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                  path('social-auth/', include('social_django.urls', namespace='social-auth')),


                  # path('accounts/', include('django.contrib.auth.urls')),
                  # path('', TemplateView.as_view(template_name='registration/studentlogin.html'), name='login'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


# Create your models here.
class PublishedPostManager(models.Manager):
    """Custom Blog Post Manager to manage posts"""

    class Meta:
        app_label = 'blog'

    def get_queryset(self):
        return super(PublishedPostManager, self).get_queryset().filter(status='published')


class BlogPost(models.Model):
    """This is a model to handles any piece of information posted on the blog"""
    # Define all the necessary fields
    CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='published_date')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    blog_body = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=15, choices=CHOICES, default='draft')
    objects = models.Manager()
    objects_published = PublishedPostManager()
    tags = TaggableManager()

    class Meta:
        app_label = 'blog'
        ordering = ('-published_date',)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Set canonical url for the blog app"""
        return reverse('blog:blog_post_detail', args=[self.published_date.year,
                                                      self.published_date.month,
                                                      self.published_date.day,
                                                      self.slug])


class Comment(models.Model):
    """Model for the comments on posts"""
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    body = RichTextField()
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        app_label = 'blog'
        ordering = ('created_date', )

    def __str__(self):
        return f"Commented by {self.name} on {self.blog_post}"

blog/forms.py
from django import forms
from .models import Comment
from ckeditor.fields import RichTextField


# Add your forms below
class EmailBlogPostForm(forms.Form):
    """Form for sharing posts via email"""
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    recipients = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class PostCommentForm(forms.ModelForm):
    """Form the comment section on posts"""
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchVectorForm(forms.Form):
    """Custom form for a search lookup"""
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailBlogPostForm, PostCommentForm, SearchVectorForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# Create your views here.
class BlogPostListView(ListView):
    """View for the list of posts"""
    queryset = BlogPost.objects_published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'posts/blog_post_list.html'


def blog_post_list(request, slug_tag=None):
    """View of all the posts"""
    tag = None
    post_list = BlogPost.objects_published.all()

    if slug_tag:
        tag = get_object_or_404(Tag, slug=slug_tag)
        post_list = post_list.filter(tags__in=[tag])
    # Create Paginator object
    paginate_posts = Paginator(post_list, 9)
    page = request.GET.get('page')
    try:
        posts = paginate_posts.page(page)
    except PageNotAnInteger:
        # Deliver the first page
        posts = paginate_posts.page(1)
    except EmptyPage:
        # Deliver last page
        posts = paginate_posts.page(paginate_posts.num_pages)

    total_posts = [i for i in range(len(posts)) ]

    post_data = zip(posts, total_posts)
    # Return HTTP response
    return render(request, 'posts/blog_post_list.html', {'posts': posts,
                                                         'page': page,
                                                         'tag': tag,
                                                         'post_data': post_data})


def blog_post_detail(request, year, month, day, post):
    """Details for a single blog post"""

    blog_post = get_object_or_404(BlogPost, slug=post,
                                  status='published',
                                  published_date__year=year,
                                  published_date__month=month,
                                  published_date__day=day)
    # Comments on the post
    post_comments = blog_post.comments.filter(active=True)
    comment_post = None

    # templatetags ids
    post_ids = blog_post.tags.values_list('id', flat=True)
    # Identical posts
    identical_posts = BlogPost.objects_published.filter(tags__in=post_ids).exclude(id=blog_post.id)
    identical_posts = identical_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published_date')[:4]

    if request.method == 'POST':
        # Comment has been posted
        post_comment_form = PostCommentForm(data=request.POST)
        if post_comment_form.is_valid():
            # Create comment object without saving it to database
            comment_post = post_comment_form.save(commit=False)
            comment_post.blog_post = blog_post # Assign current comment to comment
            comment_post.save() # Save to database
    else:
        post_comment_form = PostCommentForm()

    # Return HTTp response
    return render(request, 'posts/blog_post_detail.html', {'post': blog_post,
                                                           'comments': post_comments,
                                                           'comment_post': comment_post,
                                                           'post_comment_form': post_comment_form,
                                                           'identical_posts': identical_posts
                                                           })


def sharing_post(request, blog_post_id):
    """View to handle the sharing posts functionality"""
    blog_post = get_object_or_404(BlogPost, id=blog_post_id, status='published')  # Retrieve posts by id
    send_post = False
    if request.method == 'POST':
        # Form has been submitted
        sharing_form = EmailBlogPostForm(request.POST)
        # Check validation of fields
        if sharing_form.is_valid():
            cd = sharing_form.cleaned_data
            post_url = request.build_absolute_uri(blog_post.get_absolute_url())
            subject = f"You have a recommendation to read {blog_post.title} from {cd['name']}"
            message = f"Read {blog_post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'stewartvas01@gmail.com', [cd['recipients']])
            send_post = True

    else:
        sharing_form = EmailBlogPostForm()

    # Return HTTP response
    return render(request, 'posts/sharing_post.html', {'post': blog_post, 'form': sharing_form, 'sent': send_post})


def search_engine(request):
    """Custom View for for posts search"""
    # Initially empty query, result and form
    query = None
    form = SearchVectorForm()
    vector = TrigramSimilarity('title', 'blog_body')
    query = SearchQuery(query)
    search_result = []
    if 'query' in request.GET:
        form = SearchVectorForm(request.GET)
        # Validate form
        if form.is_valid():
            query = form.cleaned_data['query']
            search_result = BlogPost.objects_published.annotate(similarity=vector,
                                                                ).filter(similarity__gte=0.1).order_by('-similarity')
    return render(request, 'posts/search.html', {'form': form,
                                                 'query': query,
                                                 'search_result': search_result})

blog/templates/posts/blog_post_detail.html
<!DOCTYPE html>
<html lang="en">
{% extends "blogbase.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load blog_tags %}

<head>
        <!-- Required meta templatetags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--Custom CSS-->
     <link href="{% static 'languages/styles.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'blog/blogstyles.css' %}" type="text/css">

    <title>{% block title %} {{ post.title} {% endblock %}</title>
</head>

<body>
    {% block content %}
    <div class="py-5">
        <h1 class="text-primary">{{ post.title }}</h1>
        <p id="date">
            Published on {{ post.published_date }} by {{ post.author.first_name }} {{ post.author.last_name }}
        </p>
        {{ post.blog_body|markdown }}
        <p>
            <a href="{% url 'blog:sharing_post' post.id %}">Share</a>
        </p>
        {% with comments.count as total %}
        <h2>{{ total }} comment {{ total|pluralize }}</h2>
        {% endwith %}
        {% for comment in comments %}
        <div>
            <p>
                Comment {{ forloop.counter }} by {{ comment.name }} on
                {{ comment.created_date }}
            </p>
            {{ comment.body | linebreaks }}
        </div>
        {% empty %}
        <p>No comments yet.</p>
        {% endfor %}
        {% if comment_post %}
        <h2>Comment has been added.</h2>
        {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {% bootstrap_form post_comment_form %}
            {% csrf_token %}
            <button type="submit" value="Send e-mail">Add comment</button>
        </form>
        {% endif %}
        <div class="py-5">
            <h2>Most similar</h2>
            {% for post in identical_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
            {% empty %}
            No similar or identical posts yet
            {% endfor %}
        </div>
    </div>

    {% endblock %}

  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });
    </script>
</body>

</html>

blog/templates/posts/blog_post_list.html
<!DOCTYPE html>
<html lang="en">
{% extends "blogbase.html" %}
{% load static %}
{% load blog_tags %}

<head>
    <!-- Required meta templatetags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--Custom CSS-->
   <link href="{% static 'languages/styles.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'blog/blogstyles.css' %}" rel="stylesheet" type="text/css">

    <title>{% block title %} My Post list {% endblock %}</title>
</head>

<body>
    {% block content %}
    <h1 class="text-center py-5 text-primary">Posts</h1>
    {% if tag %}
    <h2>Below are the posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    <div class="row my-5 text-center">
        {% for post in posts %}
         <div class="col">
            <div class="card" style="width: 15.5rem;">
                <div class="card-body text-dark">
                    <h5 class="card-title text-primary text-center">{{ post.title }}</h5>
                    <p class="tags">
                        Tags:
                        {% for tag in post.tags.all %}
                        <a href="{% url 'blog:blog_post_list_with_tag' tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %},
                        {% endif %}
                        {% endfor %}
                    <p id="date">Published on {{ post.published_date}} by {{ post.author.first_name }} {{ post.author.last_name }}</p>
                    <p class="card-text">{{ post.blog_body|markdown|truncatewords_html:40}}</p>

                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read more</a>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}
    </div>
    <div class="row my-5 text-center">
        {% endif %}
        {% endfor %}
    </div>
    {% include "pagination.html" with page=posts %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });
    </script>

</body>

</html>

blog/templates/posts/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
    </li>
     {% endfor %}
  </ul>

blog/templates/posts/search.html
<!DOCTYPE html>
<html lang="en">
{% extends "blogbase.html" %}
{% load static %}
{% load blog_tags %}

<head>
    <!-- Required meta templatetags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">



    <title>{% block title %} Search Posts{% endblock %}</title>
</head>

<body>
    {% block content %}
    {% if query %}
    <h1>Search Results for "{{ query }}"</h1>
    <h3>
        {% with search_result.count as all_results %}
        Found {{ all_results }} result{{ all_results | pluralize }}
        {% endwith %}
    </h3>
    {% for result in search_result %}
    <h4>
        <a href="{ result.get_absolute_url }">{{ result.title }}</a>
    </h4>
    {{ result.blog_body|markdown|truncatewords_html:4 }}
    {% empty %}
    <p>No results found for search.</p>
    {% endfor %}
    <p><a href="{% url 'blog:search_post' %}">Search again</a></p>
    {% else %}
    <h1>Search for posts</h1>
    <form class="form-inline my-2 my-lg-0" method="get">
        {{ form.as_p }}
        <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
    </form>
    {% endif %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });
    </script>

</body>

</html>

blog/templates/posts/sharing_post.html
<!DOCTYPE html>
<html lang="en">
{% extends "blogbase.html" %}
{% load django_bootstrap5 %}
{% load static %}

<head>
        <!-- Required meta templatetags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

     <!--Custom CSS-->
    <link href="{% static 'languages/styles.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'blog/blogstyles.css' %}" type="text/css">

    <title>{% block title %}Share a post {% endblock %}</title>
</head>

<body>
        {% block content %}
        <div class="py-5">
        {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" has successfully been sent to {{ form.cleaned_data.recipients }}.
        </p>
        {% else %}
        <h1>Share Post "{{ blog_post.title }}" by e-mail</h1>
        <form method="post">
            {% bootstrap_form form %}
            {% csrf_token %}
            <button type="submit" value="Send e-mail">Send e-mail</button>
        </form>
        {% endif %}
        </div>
           <div class="py-5">
            <div class="py-5">
                <div class="py-5">
            </div>
        </div>
        </div>
        {% endblock %}


      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
          $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });
    </script>
</body>

</html>